# Generated by Django 3.2.16 on 2023-04-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('d_chat', models.CharField(max_length=150)),
                ('u_chat', models.CharField(max_length=150)),
                ('datetme', models.CharField(max_length=150)),
            ],
        ),
    ]
